# ***Welcome to numpy tutorial***

In [1]:
import numpy as np

In [2]:
myarr= np.array([[3,6,33,7]], np.int64)

In [3]:
myarr

array([[ 3,  6, 33,  7]], dtype=int64)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]= 45

In [7]:
myarr

array([[ 3, 45, 33,  7]], dtype=int64)

In [8]:
myarr

array([[ 3, 45, 33,  7]], dtype=int64)

# **Array Creation: Conversion from other Python structures**

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,22,21})

array({34, 21, 22}, dtype=object)

In [15]:
np.array({32,21,21})

array({32, 21}, dtype=object)

# **Array Creation: Intrinsic numpy array creation objects**

In [16]:
zeros= np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
rng= np.arange(15)#it actually used to create a numpy array

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lnspace= np.linspace(1,5,12)

In [23]:
lnspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
lnspace= np.linspace(1,50,3)

In [25]:
lnspace

array([ 1. , 25.5, 50. ])

In [26]:
emp= np.empty((4,6))

In [27]:
emp

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [28]:
emp_like= np.empty_like(lnspace) #it actually copies the size of the previous array

In [29]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [30]:
ide= np.identity(3)

In [31]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
ide.shape

(3, 3)

In [33]:
ide.size

9

In [34]:
arr= np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
ar= arr.ravel()

In [38]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [40]:
arr.shape

(99,)

In [41]:
x= [[1,2,3],[4,5,6],[7,8,9]]

In [42]:
ar= np.array(x)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar.sum(axis= 1)

array([ 6, 15, 24])

In [45]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
ar.ndim #no.of dimensions

2

In [49]:
ar.nbytes

36

In [50]:
one= np.array([1,3,4,634,2])

In [51]:
one.argmax()#now this is a function or method which return the index of maximum element

3

In [52]:
one.argmin()

0

In [53]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [56]:
ar.argmin()

0

In [57]:
ar.argmax()

8

In [58]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [59]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [60]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [61]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
ar2= np.array([[1, 0, 3],
       [2, 1, 0],
       [1, 3, 2]])

In [64]:
ar2

array([[1, 0, 3],
       [2, 1, 0],
       [1, 3, 2]])

In [65]:
ar+ar2

array([[ 2,  2,  6],
       [ 6,  6,  6],
       [ 8, 11, 11]])

In [66]:
ar*ar2

array([[ 1,  0,  9],
       [ 8,  5,  0],
       [ 7, 24, 18]])

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
np.sqrt(ar2)

array([[1.        , 0.        , 1.73205081],
       [1.41421356, 1.        , 0.        ],
       [1.        , 1.73205081, 1.41421356]])

In [69]:
ar.sum()

45

In [70]:
ar2.max()

3

In [71]:
ar.min()

1

In [72]:
np.where(ar<1)

(array([], dtype=int64), array([], dtype=int64))

In [73]:
type(np.where(ar2<1))

tuple

In [74]:
np.where(ar>1)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [75]:
np.count_nonzero(ar)

9

In [76]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [77]:
np.nonzero(ar2)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 0, 1, 2], dtype=int64))

In [78]:
ar2[1,0]=0

In [79]:
np.nonzero(ar2)

(array([0, 0, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 1, 0, 1, 2], dtype=int64))

In [80]:
import sys

In [81]:
py_ar=[0,4,55,2]

In [82]:
np_ar=np.array(py_ar)

In [83]:
sys.getsizeof(1) * len(py_ar)

112

In [84]:
np_ar.itemsize * np_ar.size

16